# Generated by Django 6.0.3 on 2026-03-10 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="nombre_paquete",
            field=models.CharField(
                blank=True,
                default="Caja",
                help_text="Nombre del paquete (ej: Caja, Paquete, Bolsa, Cartón)",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="producto",
            name="precio_venta_paquete",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Precio al vender el paquete completo (dejar vacío si no aplica)",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="producto",
            name="unidades_por_paquete",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Unidades que contiene cada paquete/caja (1 = no aplica fraccionado)",
            ),
        ),
    ]
