# Generated by Django 6.0.3 on 2026-03-10 17:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0002_producto_nombre_paquete_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="proveedor",
            name="activo",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="proveedor",
            name="celular",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="proveedor",
            name="ciudad",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="proveedor",
            name="condicion_pago",
            field=models.CharField(
                choices=[
                    ("contado", "Contado"),
                    ("7dias", "Crédito 7 días"),
                    ("15dias", "Crédito 15 días"),
                    ("30dias", "Crédito 30 días"),
                    ("60dias", "Crédito 60 días"),
                ],
                default="contado",
                max_length=10,
                verbose_name="Condición de pago",
            ),
        ),
        migrations.AddField(
            model_name="proveedor",
            name="direccion",
            field=models.CharField(
                blank=True, max_length=250, verbose_name="Dirección"
            ),
        ),
        migrations.AddField(
            model_name="proveedor",
            name="fecha_registro",
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddField(
            model_name="proveedor",
            name="nit",
            field=models.CharField(blank=True, max_length=30, verbose_name="NIT / RUC"),
        ),
        migrations.AddField(
            model_name="proveedor",
            name="notas",
            field=models.TextField(blank=True, verbose_name="Notas internas"),
        ),
        migrations.AddField(
            model_name="proveedor",
            name="sitio_web",
            field=models.URLField(blank=True, verbose_name="Sitio web"),
        ),
        migrations.AlterField(
            model_name="proveedor",
            name="contacto",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Nombre del contacto"
            ),
        ),
    ]
