# Generated by Django 6.0.3 on 2026-03-10 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ventas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemventa",
            name="es_paquete",
            field=models.BooleanField(
                default=False, help_text="True si se vendió como paquete/caja completa"
            ),
        ),
        migrations.AddField(
            model_name="itemventa",
            name="unidades_descontadas",
            field=models.PositiveIntegerField(
                default=0, help_text="Unidades reales descontadas del stock"
            ),
        ),
    ]
