# Generated by Django 6.0 on 2026-03-11 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ConfiguracionTienda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre_tienda",
                    models.CharField(
                        default="Tienda de Abarrotes",
                        max_length=100,
                        verbose_name="Nombre de la tienda",
                    ),
                ),
                (
                    "slogan",
                    models.CharField(
                        blank=True,
                        default="Sistema de Gestión",
                        max_length=200,
                        verbose_name="Eslogan / subtítulo",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="config/", verbose_name="Logo"
                    ),
                ),
                (
                    "color_primary",
                    models.CharField(
                        default="#1a6b3c", max_length=7, verbose_name="Color primario"
                    ),
                ),
                (
                    "color_primary_dark",
                    models.CharField(
                        default="#124d2b",
                        max_length=7,
                        verbose_name="Color primario oscuro",
                    ),
                ),
                (
                    "color_accent",
                    models.CharField(
                        default="#f59e0b", max_length=7, verbose_name="Color de acento"
                    ),
                ),
                (
                    "tema",
                    models.CharField(
                        choices=[("claro", "Claro"), ("oscuro", "Oscuro")],
                        default="claro",
                        max_length=10,
                        verbose_name="Tema",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuración de Tienda",
            },
        ),
    ]
